name = "PhaseRetrieval"
uuid = "dce5fc76-fdf2-4205-8357-5df4580ffcb1"
authors = ["Yong-an Lu <miroox@outlook.com>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
Distances = "0.10"
FFTW = "1"
julia = "1.4"
