name = "PhaseRetrieval"
uuid = "dce5fc76-fdf2-4205-8357-5df4580ffcb1"
authors = ["Yong-an Lu <miroox@outlook.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
julia = "1.4"
FFTW = "1"
